# Generated by Django 4.0.5 on 2022-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarBuySell', '0002_rename_firstname_members_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('Present_Price', models.CharField(max_length=255)),
                ('Kms_Driven', models.CharField(max_length=255)),
                ('Owner', models.CharField(max_length=255)),
                ('Age', models.CharField(max_length=255)),
                ('Fuel_Type', models.CharField(max_length=255)),
                ('Seller_Type', models.CharField(max_length=255)),
                ('Transmission', models.CharField(max_length=255)),
            ],
        ),
    ]
