# Generated by Django 4.0.5 on 2022-06-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarBuySell', '0004_cars_compmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='Pred_Price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
