# Generated by Django 4.0.5 on 2022-07-30 16:53

import CarBuySell.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarBuySell', '0005_cars_pred_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=CarBuySell.models.filepath),
        ),
    ]
